export {};

/**
 * Adds this app's own bindings, declared in wrangler.jsonc, to
 * `@opennextjs/cloudflare`'s global `CloudflareEnv` (see
 * node_modules/@opennextjs/cloudflare/dist/api/cloudflare-context.d.ts), so
 * `getCloudflareContext().env.RATE_LIMIT_AUTH` is typed.
 *
 * Hand-written rather than generated by `npx wrangler types` or taken from
 * `@cloudflare/workers-types`: either of those replaces global DOM types with
 * the Workers runtime's (e.g. `Body.json()` returns `Promise<unknown>`
 * instead of `Promise<any>`), which breaks ordinary route handler code for the
 * sake of one small interface. Not named `cloudflare-env.d.ts` because
 * .gitignore reserves that name for `wrangler types` output.
 *
 * Optional on purpose: the bindings exist only on Workers (and in `next dev` /
 * `preview`), not under `next start`, and checkBurst() falls back when they're
 * missing. Add one here when you add a binding to wrangler.jsonc.
 */
declare global {
  /** A Workers rate-limit binding (`ratelimits` in wrangler.jsonc) — see src/lib/rate-limit/burst.ts. */
  interface RateLimitBinding {
    limit(options: { key: string }): Promise<{ success: boolean }>;
  }

  interface CloudflareEnv {
    RATE_LIMIT_AUTH?: RateLimitBinding;
    RATE_LIMIT_BILLING?: RateLimitBinding;
  }
}
